version:     "0007--20-Jan-2022"
copyright:   "2022-2022"
description:
  Laman ini berisi presentasi BackUp dengan RSYNC dan GIT.
disclaimer:
  I have spoken.
keywords:    "demosuremo"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Tips"
  link:      "/TIPS/"
- navbar:    "GitHub"
  link:      "https://github.com/demosuremo/demo/"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "About"
  link:      "/ABOUT/"
- navbar:    "GitHub Page"
  link:      "https://demosuremo.github.io/demo/"
title:       "BackUp dengan RSYNC dan GIT"
lang:        "en-US"
author:      "Demo Suremo"
address:     "Ternate, Halmahera."
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-16"
urlweb:           "https://demosuremo.github.io/demo/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/demosuremo/demo/"

keep_files: [ISO]
